name: Setup Documentation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Current Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate Docs with Donovan
        run: npx donovan 
      - name: Create Documentation Branch
        run: |
          git config --local user.email "fairfieldprogramming@gmail.com"
          git config --local user.name "fairfield-programming-bot"
          git commit -a -m "Uploaded New Documentation"
          git branch docs
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
